name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          # files: |
          #   LICENSE.txt
          #   *.jar
  # createrelease:
  #   name: Create Release
  #   runs-on: [ubuntu-latest]
  #   steps:
  #   - name: Create Release
  #     id: create_release
  #     uses: actions/create-release@v1
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       tag_name: ${{ github.ref }}
  #       release_name: Release ${{ github.ref }}
  #       draft: false
  #       prerelease: false
  #   - name: Output Release URL File
  #     run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
  #   - name: Save Release URL File for publish
  #     uses: actions/upload-artifact@v1
  #     with:
  #       name: release_url
  #       path: release_url.txt

  build:
    name: Build packages
    # needs: createrelease
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
                pyinstaller -F -w -n LinearStitch LS_GUI.py &&
                cd dist/ &&
                zip -r9 LinearStitch LinearStitch.app/
            OUT_FILE_NAME: LinearStitch.zip
            ASSET_MIME: application/zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller -F -w -n LinearStitch LS_GUI.py
            OUT_FILE_NAME: LinearStitch.exe
            ASSET_MIME: application/vnd.microsoft.portable-executable
    steps:
    - run: echo "HELLO"
    - run: echo ${GITHUB_REPOSITORY}
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with pyinstaller for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: dist/*
        name: LinearStitch ${{ matrix.os }} binary
  release:
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2
        with:
          path: linearstitch
          fetch-depth: "0"
      
      - name: Download artifacts
        run: |
          mkdir -p dist
          cd dist
          gh run --repo ${GITHUB_REPOSITORY} download -n 'LinearStitch macos-latest binary'
          gh run --repo ${GITHUB_REPOSITORY} download -n 'LinearStitch windows-latest binary'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: List artifacts
        run: |
          find dist
      
      - name: Upload to latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'
        run: |
          cd dist
          gh api repos/${GITHUB_REPOSITORY}/releases/tags/latest | jq -r '.assets[] | [.url] | @tsv' | xargs -n 1 gh api -X DELETE || true
          gh release upload --repo ${GITHUB_REPOSITORY} --clobber latest *zip
          gh release upload --repo ${GITHUB_REPOSITORY} --clobber latest *exe